apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-astro-certificate
  namespace: default
spec:
  secretName: blog-astro-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - blog.facturameya.online
